name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Docker Login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |        
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD       
    
    - name: Build Docker Image
      run: |
        docker build -t gastonfernandez78/docker-graphql:0.0.2 .

    - name: Docker Push Image
      run: |
        docker push gastonfernandez78/docker-graphql:0.0.2
    
    
    
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
